name: windows

on: [push, pull_request]

jobs:
  test-powershell:
    name: Test on PowerShell on Windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install powershell-yaml
      shell: powershell
      run: |
        $ErrorActionPreference = 'Stop'
        Install-Module powershell-yaml -Force
    - name: Install Pester
      shell: powershell
      run: |
        $ErrorActionPreference = 'Stop'
        Install-Module Pester -Force -SkipPublisherCheck -MaximumVersion 4.10.1
    - name: Test
      shell: powershell
      run: |
        $ErrorActionPreference = 'Stop'
        Import-Module Pester
        Invoke-Pester -EnableExit

  test-pwsh:
    name: Test on PowerShell Core on Windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install powershell-yaml
      shell: pwsh
      run: |
        $ErrorActionPreference = 'Stop'
        Install-Module powershell-yaml -Force
    - name: Install Pester
      shell: pwsh
      run: |
        $ErrorActionPreference = 'Stop'
        Install-Module Pester -Force -SkipPublisherCheck -MaximumVersion 4.10.1
    - name: Test
      shell: pwsh
      run: |
        $ErrorActionPreference = 'Stop'
        Import-Module Pester
        Invoke-Pester -EnableExit

  lint:
    name: Lint by PSScriptAnalyzer
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install PSScriptAnalyzer
      shell: pwsh
      run: |
        $ErrorActionPreference = 'Stop'
        Install-Module PSScriptAnalyzer -Force
    - name: Lint
      shell: pwsh
      run: |
        $ErrorActionPreference = 'Stop'
        Import-Module PSScriptAnalyzer
        Invoke-ScriptAnalyzer . -Recurse -Severity Information -EnableExit
